# Escolher uma imagem base - FROM
FROM nginx
# Copiar arquivo para dentro do container - COPY
COPY index.html /usr/share/nginx/html
# Criando a imagem - docker build -t -p 3000:80 gustavo/hello-nginx . na porta 3000*
RUN echo hello-nginx
