version: '3'

services:
  web:
    build: .
    image: ubuntu/nginx:latest # pull nginx
    volumes:
      - ./public_html:/usr/share/nginx/html # docker volume create "..."
    ports: # docker run -p 8080:80
      - 8080:80 

# docker-compose up inicia o container
# docker-compose down para o container

